[pytest]
# 指定用例存放目录
testpaths = testcases
# 用例文件、类、函数命名规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# 控制台实时打印日志
log_cli = true
log_cli_level = INFO
# 执行参数：控制台详细输出、allure原始数据路径、统计覆盖率
addopts = --alluredir=reports/allure_raw -v -s --cov=common,page,utils